name: 'Get repository ID'
description: 'Gets the ID of the specified GitHub repository'
author: 'Noelia Ruiz Martínez'

# Define your inputs here.
inputs:
  repository:
    description: 'Repository name with owner. For example, nvdaes/getRepositoryId'
    required: true
    default: ${{ github.repository }}
  token:
    description: 'GitHub token'
    required: true
    default: ${{ secrets.GITHUB_TOKEN }}

# Define your outputs here.
outputs:
  repoId:
    description: 'The ID of the specified repository'

runs:
  using: node20
  main: dist/index.js
